# 🏥 Análise da Rede Hospitalar do Rio de Janeiro

## Objetivo

Este projeto tem como objetivo analisar os estabelecimentos de saúde do estado do Rio de Janeiro, explorando informações sobre municípios, tipos de unidades, leitos hospitalares e leitos de UTI.

A análise será desenvolvida utilizando Python, Pandas e posteriormente Power BI para construção de visualizações e indicadores.

O projeto seguirá uma arquitetura de dados em camadas:

- 🥉 Bronze — dados brutos e exploração inicial;
- 🥈 Silver — limpeza, tratamento e padronização;
- 🥇 Gold — dados analíticos preparados para consumo e visualização.

## 2. Importação da biblioteca Pandas

A biblioteca `pandas` será utilizada para leitura, manipulação e análise dos dados.

## 3. Carregamento da base de dados

Nesta etapa, o arquivo CSV contendo os dados dos estabelecimentos de saúde será carregado para um DataFrame.
O DataFrame permite trabalhar com os dados em formato de tabela dentro do Python.

In [54]:
import pandas as pd
hospi_rio = pd.read_csv(r'C:\Users\lokiz\OneDrive\Documentos\projeto_hospitalar_rio\bronze\Leitos_2026.csv', sep=';', encoding='latin1')
hospi_rio

,COMP,REGIAO,UF,CO_IBGE,MUNICIPIO,MOTIVO_DESABILITACAO,CNES,NOME_ESTABELECIMENTO,RAZAO_SOCIAL,TP_GESTAO,...,UTI_ADULTO_EXIST,UTI_ADULTO_SUS,UTI_PEDIATRICO_EXIST,UTI_PEDIATRICO_SUS,UTI_NEONATAL_EXIST,UTI_NEONATAL_SUS,UTI_QUEIMADO_EXIST,UTI_QUEIMADO_SUS,UTI_CORONARIANA_EXIST,UTI_CORONARIANA_SUS
0,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,27,CASA DE SAUDE SANTA HELENA,CASA DE SAUDE E MATERNIDADE SANTA HELENA LTDA,M,...,0,0,0,0,0,0,0,0,0,0
1,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,35,HOSPITAL MENDO SAMPAIO,PREFEITURA MUNICIPAL DO CABO DE SANTO AGOSTINHO,M,...,0,0,0,0,0,0,0,0,0,0
2,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,94,MATERNIDADE PADRE GERALDO LEITE BASTOS,PREFEITURA MUNICIPAL DO CABO DE SANTO AGOSTINHO,M,...,0,0,0,0,0,0,0,0,0,0
3,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,183,HOSPITAL SAMARITANO,SOCIEDADE HOSPITALAR SAMARITANO LTDA,M,...,0,0,0,0,0,0,0,0,0,0
4,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,221,HOSPITAL SAO SEBASTIAO,CASA DE SAUDE E MATERNIDADE SAO SEBASTIAO LTDA,M,...,10,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43175,202606,NORDESTE,PB,250970,MONTEIRO,NaN,9954279,HOSPITAL DIA SANTA MARIA,CENTRO MEDICO MAYER E FEITOSA LTDA,M,...,0,0,0,0,0,0,0,0,0,0
43176,202606,SUDESTE,SP,355060,SAO ROQUE,NaN,9966900,HOSPITAL SAO FRANCISCO,HOSPITAL SAO FRANCISCO EIRELI,M,...,0,0,0,0,0,0,0,0,0,0
43177,202606,SUDESTE,SP,352250,ITAPEVI,NaN,9997032,HOSPITAL YES,HOSPITAL YES LTDA,M,...,40,0,0,0,0,0,0,0,0,0
43178,202606,NORDESTE,PB,250460,CONDE,NaN,9997172,CLINICA MEDICA PERSONNALITE,CLINICA MEDICA PERSONNALITE LTDA,M,...,0,0,0,0,0,0,0,0,0,0
43179,202606,NORDESTE,MA,210125,BACABEIRA,NaN,9997784,HOSPITAL E MATERNIDADE NAILA GONCALO,MUNICIPIO DE BACABAEIRA,M,...,0,0,0,0,0,0,0,0,0,0

## 4. Visualização inicial dos dados

O método `head()` permite visualizar as primeiras linhas do DataFrame.

Essa etapa é importante para verificar se os dados foram carregados corretamente e conhecer inicialmente a estrutura das informações.

In [55]:
hospi_rio.head()

,COMP,REGIAO,UF,CO_IBGE,MUNICIPIO,MOTIVO_DESABILITACAO,CNES,NOME_ESTABELECIMENTO,RAZAO_SOCIAL,TP_GESTAO,...,UTI_ADULTO_EXIST,UTI_ADULTO_SUS,UTI_PEDIATRICO_EXIST,UTI_PEDIATRICO_SUS,UTI_NEONATAL_EXIST,UTI_NEONATAL_SUS,UTI_QUEIMADO_EXIST,UTI_QUEIMADO_SUS,UTI_CORONARIANA_EXIST,UTI_CORONARIANA_SUS
0,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,27,CASA DE SAUDE SANTA HELENA,CASA DE SAUDE E MATERNIDADE SANTA HELENA LTDA,M,...,0,0,0,0,0,0,0,0,0,0
1,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,35,HOSPITAL MENDO SAMPAIO,PREFEITURA MUNICIPAL DO CABO DE SANTO AGOSTINHO,M,...,0,0,0,0,0,0,0,0,0,0
2,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,94,MATERNIDADE PADRE GERALDO LEITE BASTOS,PREFEITURA MUNICIPAL DO CABO DE SANTO AGOSTINHO,M,...,0,0,0,0,0,0,0,0,0,0
3,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,183,HOSPITAL SAMARITANO,SOCIEDADE HOSPITALAR SAMARITANO LTDA,M,...,0,0,0,0,0,0,0,0,0,0
4,202601,NORDESTE,PE,260290,CABO DE SANTO AGOSTINHO,NaN,221,HOSPITAL SAO SEBASTIAO,CASA DE SAUDE E MATERNIDADE SAO SEBASTIAO LTDA,M,...,10,0,0,0,0,0,0,0,0,0

## 5. Visualização das últimas linhas

O método `tail()` permite visualizar as últimas linhas do DataFrame.

Essa verificação ajuda a confirmar se o arquivo foi carregado completamente.

In [56]:
hospi_rio.tail()

,COMP,REGIAO,UF,CO_IBGE,MUNICIPIO,MOTIVO_DESABILITACAO,CNES,NOME_ESTABELECIMENTO,RAZAO_SOCIAL,TP_GESTAO,...,UTI_ADULTO_EXIST,UTI_ADULTO_SUS,UTI_PEDIATRICO_EXIST,UTI_PEDIATRICO_SUS,UTI_NEONATAL_EXIST,UTI_NEONATAL_SUS,UTI_QUEIMADO_EXIST,UTI_QUEIMADO_SUS,UTI_CORONARIANA_EXIST,UTI_CORONARIANA_SUS
43175,202606,NORDESTE,PB,250970,MONTEIRO,NaN,9954279,HOSPITAL DIA SANTA MARIA,CENTRO MEDICO MAYER E FEITOSA LTDA,M,...,0,0,0,0,0,0,0,0,0,0
43176,202606,SUDESTE,SP,355060,SAO ROQUE,NaN,9966900,HOSPITAL SAO FRANCISCO,HOSPITAL SAO FRANCISCO EIRELI,M,...,0,0,0,0,0,0,0,0,0,0
43177,202606,SUDESTE,SP,352250,ITAPEVI,NaN,9997032,HOSPITAL YES,HOSPITAL YES LTDA,M,...,40,0,0,0,0,0,0,0,0,0
43178,202606,NORDESTE,PB,250460,CONDE,NaN,9997172,CLINICA MEDICA PERSONNALITE,CLINICA MEDICA PERSONNALITE LTDA,M,...,0,0,0,0,0,0,0,0,0,0
43179,202606,NORDESTE,MA,210125,BACABEIRA,NaN,9997784,HOSPITAL E MATERNIDADE NAILA GONCALO,MUNICIPIO DE BACABAEIRA,M,...,0,0,0,0,0,0,0,0,0,0

## 6. Dimensão da base

O atributo `shape` informa a quantidade de linhas e colunas existentes no DataFrame.

O primeiro valor representa a quantidade de registros e o segundo representa a quantidade de colunas.

In [57]:
hospi_rio.shape

(43180, 35)

## 7. Identificação das colunas

O atributo `columns` retorna os nomes das colunas existentes no DataFrame.

Essa etapa permite conhecer quais informações estão disponíveis para análise.

In [58]:
hospi_rio.columns

Index(['COMP', 'REGIAO', 'UF', 'CO_IBGE', 'MUNICIPIO', 'MOTIVO_DESABILITACAO',
       'CNES', 'NOME_ESTABELECIMENTO', 'RAZAO_SOCIAL', 'TP_GESTAO',
       'CO_TIPO_UNIDADE', 'DS_TIPO_UNIDADE', 'NATUREZA_JURIDICA',
       'DESC_NATUREZA_JURIDICA', 'NO_LOGRADOURO', 'NU_ENDERECO',
       'NO_COMPLEMENTO', 'NO_BAIRRO', 'CO_CEP', 'NU_TELEFONE', 'NO_EMAIL',
       'LEITOS_EXISTENTES', 'LEITOS_SUS', 'UTI_TOTAL_EXIST', 'UTI_TOTAL_SUS',
       'UTI_ADULTO_EXIST', 'UTI_ADULTO_SUS', 'UTI_PEDIATRICO_EXIST',
       'UTI_PEDIATRICO_SUS', 'UTI_NEONATAL_EXIST', 'UTI_NEONATAL_SUS',
       'UTI_QUEIMADO_EXIST', 'UTI_QUEIMADO_SUS', 'UTI_CORONARIANA_EXIST',
       'UTI_CORONARIANA_SUS'],
      dtype='str')

## 8. Informações estruturais da base

O método `info()` apresenta informações sobre a estrutura do DataFrame.

Ele permite verificar:

- quantidade de registros;
- nomes das colunas;
- tipos de dados;
- quantidade de valores não nulos;
- uso aproximado de memória.

In [59]:
hospi_rio.info()

<class 'pandas.DataFrame'>
RangeIndex: 43180 entries, 0 to 43179
Data columns (total 35 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   COMP                    43180 non-null  int64
 1   REGIAO                  43180 non-null  str
 2   UF                      43180 non-null  str
 3   CO_IBGE                 43180 non-null  int64
 4   MUNICIPIO               43180 non-null  str
 5   MOTIVO_DESABILITACAO    0 non-null      float64
 6   CNES                    43180 non-null  int64
 7   NOME_ESTABELECIMENTO    43180 non-null  str
 8   RAZAO_SOCIAL            43180 non-null  str
 9   TP_GESTAO               43180 non-null  str
 10  CO_TIPO_UNIDADE         43180 non-null  int64
 11  DS_TIPO_UNIDADE         43180 non-null  str
 12  NATUREZA_JURIDICA       43180 non-null  int64
 13  DESC_NATUREZA_JURIDICA  43180 non-null  str
 14  NO_LOGRADOURO           43180 non-null  str
 15  NU_ENDERECO             43175 non-null  str
 16  NO_COMPLEMENTO          8529 non-null   str
 17  NO_BAIRRO               43180 non-null  str
 18  CO_CEP                  43180 non-null  int64
 19  NU_TELEFONE             38056 non-null  str
 20  NO_EMAIL                29570 non-null  str
 21  LEITOS_EXISTENTES       43180 non-null  int64
 22  LEITOS_SUS              43180 non-null  int64
 23  UTI_TOTAL_EXIST         43180 non-null  int64
 24  UTI_TOTAL_SUS           43180 non-null  int64
 25  UTI_ADULTO_EXIST        43180 non-null  int64
 26  UTI_ADULTO_SUS          43180 non-null  int64
 27  UTI_PEDIATRICO_EXIST    43180 non-null  int64
 28  UTI_PEDIATRICO_SUS      43180 non-null  int64
 29  UTI_NEONATAL_EXIST      43180 non-null  int64
 30  UTI_NEONATAL_SUS        43180 non-null  int64
 31  UTI_QUEIMADO_EXIST      43180 non-null  int64
 32  UTI_QUEIMADO_SUS        43180 non-null  int64
 33  UTI_CORONARIANA_EXIST   43180 non-null  int64
 34  UTI_CORONARIANA_SUS     43180 non-null  int64
dtypes: float64(1), int64(20), str(14)
memory usage: 19.1 MB

## 9. Estatísticas descritivas

O método `describe()` apresenta estatísticas descritivas das colunas numéricas.

Entre as informações apresentadas estão:

- quantidade de registros;
- média;
- desvio padrão;
- valor mínimo;
- quartis;
- valor máximo.

In [60]:
hospi_rio.describe()

,COMP,CO_IBGE,MOTIVO_DESABILITACAO,CNES,CO_TIPO_UNIDADE,NATUREZA_JURIDICA,CO_CEP,LEITOS_EXISTENTES,LEITOS_SUS,UTI_TOTAL_EXIST,...,UTI_ADULTO_EXIST,UTI_ADULTO_SUS,UTI_PEDIATRICO_EXIST,UTI_PEDIATRICO_SUS,UTI_NEONATAL_EXIST,UTI_NEONATAL_SUS,UTI_QUEIMADO_EXIST,UTI_QUEIMADO_SUS,UTI_CORONARIANA_EXIST,UTI_CORONARIANA_SUS
count,43180.000000,43180.000000,0.0,4.318000e+04,43180.000000,43180.000000,4.318000e+04,43180.000000,43180.000000,43180.000000,...,43180.000000,43180.000000,43180.000000,43180.000000,43180.000000,43180.000000,43180.000000,43180.000000,43180.000000,43180.000000
mean,202603.499375,322729.470195,NaN,3.370694e+06,6.216813,2131.350000,5.384472e+07,72.431566,49.047337,8.876633,...,6.119037,3.108082,1.060167,0.507967,1.378786,0.723344,0.034090,0.022371,0.284553,0.084206
std,1.709060,103654.263033,NaN,2.137522e+06,3.091606,1112.125985,2.550750e+07,96.064518,82.657551,19.925403,...,14.188888,9.913139,4.178024,2.720548,4.715065,3.458887,0.473231,0.338666,2.150203,0.992361
min,202601.000000,110001.000000,NaN,2.700000e+01,5.000000,1015.000000,1.037000e+06,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,202602.000000,250750.000000,NaN,2.274108e+06,5.000000,1244.000000,3.560400e+07,20.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,202603.000000,315770.000000,NaN,2.561328e+06,5.000000,2054.000000,5.848900e+07,41.000000,25.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,202605.000000,410420.000000,NaN,3.649156e+06,5.000000,3069.000000,7.486021e+07,87.000000,56.000000,10.000000,...,9.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,202606.000000,530010.000000,NaN,9.997784e+06,21.000000,3999.000000,9.998000e+07,1543.000000,1476.000000,386.000000,...,245.000000,245.000000,80.000000,56.000000,108.000000,104.000000,14.000000,7.000000,66.000000,30.000000

## 10. Identificação de valores ausentes

Nesta etapa será verificada a quantidade de valores nulos em cada coluna.

A identificação de valores ausentes é importante para avaliar a qualidade dos dados antes da etapa de tratamento.

In [61]:
hospi_rio.isnull().sum()

COMP                          0
REGIAO                        0
UF                            0
CO_IBGE                       0
MUNICIPIO                     0
MOTIVO_DESABILITACAO      43180
CNES                          0
NOME_ESTABELECIMENTO          0
RAZAO_SOCIAL                  0
TP_GESTAO                     0
CO_TIPO_UNIDADE               0
DS_TIPO_UNIDADE               0
NATUREZA_JURIDICA             0
DESC_NATUREZA_JURIDICA        0
NO_LOGRADOURO                 0
NU_ENDERECO                   5
NO_COMPLEMENTO            34651
NO_BAIRRO                     0
CO_CEP                        0
NU_TELEFONE                5124
NO_EMAIL                  13610
LEITOS_EXISTENTES             0
LEITOS_SUS                    0
UTI_TOTAL_EXIST               0
UTI_TOTAL_SUS                 0
UTI_ADULTO_EXIST              0
UTI_ADULTO_SUS                0
UTI_PEDIATRICO_EXIST          0
UTI_PEDIATRICO_SUS            0
UTI_NEONATAL_EXIST            0
UTI_NEONATAL_SUS              0
UTI_QUEIMADO_EXIST            0
UTI_QUEIMADO_SUS              0
UTI_CORONARIANA_EXIST         0
UTI_CORONARIANA_SUS           0
dtype: int64

## 10. Estados presentes na base

A coluna `UF` será analisada para identificar os estados presentes na base de dados.

O método `unique()` retorna os estados diferentes encontrados na coluna.

In [62]:
hospi_rio['UF'].unique()

<ArrowStringArray>
['PE', 'SE', 'BA', 'PA', 'SP', 'MS', 'DF', 'ES', 'RJ', 'PR', 'SC', 'GO', 'AL',
 'MG', 'AM', 'MT', 'PB', 'CE', 'RS', 'RO', 'MA', 'AC', 'RN', 'TO', 'PI', 'RR',
 'AP']
Length: 27, dtype: str

## 11. Distribuição dos registros por estado

A coluna `UF` será analisada para identificar os estados presentes na base.

O método `value_counts()` contabiliza a quantidade de ocorrências de cada estado.

In [63]:
hospi_rio['UF'].value_counts()

UF
SP    6161
MG    3981
BA    3742
RJ    2964
GO    2688
PR    2680
PE    2371
RS    1980
MA    1933
CE    1887
PA    1701
SC    1469
RN    1171
PB    1163
PI    1160
MT    1095
MS     736
ES     681
AM     678
RO     676
AL     588
TO     481
DF     399
SE     333
AC     204
AP     138
RR     120
Name: count, dtype: int64

## 12. Filtragem dos registros do Rio de Janeiro

Nesta etapa será criada uma nova tabela contendo somente os registros pertencentes ao estado do Rio de Janeiro.

A condição `UF == "RJ"` seleciona apenas as linhas em que o estado é igual a RJ.

O método `copy()` cria uma cópia independente dos dados selecionados.

Com o nome hospital_RJ

In [64]:
hospital_RJ=hospi_rio[hospi_rio['UF']=='RJ'].copy()
hospital_RJ

,COMP,REGIAO,UF,CO_IBGE,MUNICIPIO,MOTIVO_DESABILITACAO,CNES,NOME_ESTABELECIMENTO,RAZAO_SOCIAL,TP_GESTAO,...,UTI_ADULTO_EXIST,UTI_ADULTO_SUS,UTI_PEDIATRICO_EXIST,UTI_PEDIATRICO_SUS,UTI_NEONATAL_EXIST,UTI_NEONATAL_SUS,UTI_QUEIMADO_EXIST,UTI_QUEIMADO_SUS,UTI_CORONARIANA_EXIST,UTI_CORONARIANA_SUS
98,202601,SUDESTE,RJ,330330,NITEROI,NaN,12505,HOSPITAL UNIVERSITARIO ANTONIO PEDRO,EMPRESA BRASILEIRA DE SERVICOS HOSPITALARES,M,...,16,16,0,0,8,8,0,0,10,10
99,202601,SUDESTE,RJ,330330,NITEROI,NaN,12513,HOSPITAL MUNICIPAL CARLOS TORTELLY,FUNDACAO MUNICIPAL DE SAUDE,M,...,0,0,0,0,0,0,0,0,0,0
100,202601,SUDESTE,RJ,330330,NITEROI,NaN,12521,SES RJ HOSPITAL ESTADUAL AZEVEDO LIMA,SECRETARIA DE ESTADO DE SAUDE SES,E,...,35,30,0,0,10,0,0,0,0,0
101,202601,SUDESTE,RJ,330330,NITEROI,NaN,12548,HOSPITAL DA POLICIA MILITAR DE NITEROI,HOSPITAL DA POLICIA MILITAR DE NITEROI,M,...,0,0,0,0,0,0,0,0,0,0
102,202601,SUDESTE,RJ,330330,NITEROI,NaN,12556,HOSPITAL ORENCIO DE FREITAS,FUNDACAO MUNICIPAL DE SAUDE DE NITEROI,M,...,6,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43142,202606,SUDESTE,RJ,330330,NITEROI,NaN,9839674,ESSENCIAL HOSPITAL DE TRANSICAO,ESSENCIAL CARE ASSISTENCIA MEDICA,M,...,0,0,0,0,0,0,0,0,0,0
43155,202606,SUDESTE,RJ,330270,MARICA,NaN,9895124,ERNESTO CHE GUEVARA SMSM,HOSPITAL MUNICIPAL DR ERNESTO CHE GUEVARA,M,...,20,10,5,0,0,0,0,0,0,0
43156,202606,SUDESTE,RJ,330010,ANGRA DOS REIS,NaN,9903496,PLAZA MEDICAL SERVICOS ESPECIALIZADOS EM SAUDE...,PLAZA MEDICAL SERVICOS ESPECIALIZADOS EM SAUDE...,M,...,0,0,5,0,15,0,0,0,0,0
43158,202606,SUDESTE,RJ,330490,SAO GONCALO,NaN,9912584,CLISSIL,CLISSIL CLINICA SAO SILVESTRE,M,...,0,0,0,0,0,0,0,0,0,0
43163,202606,SUDESTE,RJ,330110,CANTAGALO,NaN,9921710,CTI JOAO PAULO II,CENTRO DE TRATAMENTO INTENSIVO DE CANTAGALO LTDA,M,...,10,0,0,0,0,0,0,0,0,0

## 13. Validação da filtragem

O método `shape` será utilizado novamente para confirmar a quantidade de registros e colunas após o filtro do estado do Rio de Janeiro.

In [65]:
hospital_RJ.shape

(2964, 35)

### Resultado

Após a filtragem, a base passou a conter **2.964 registros do Rio de Janeiro**, mantendo as **35 colunas** originais.

## 14. Distribuição dos registros por município

A coluna `MUNICIPIO` será analisada para identificar a quantidade de registros de estabelecimentos de saúde em cada município do Rio de Janeiro.

O método `value_counts()` será utilizado para contabilizar as ocorrências de cada município.

In [66]:
hospital_RJ['MUNICIPIO'].value_counts()

MUNICIPIO
RIO DE JANEIRO           1160
NITEROI                   192
CAMPOS DOS GOYTACAZES     114
DUQUE DE CAXIAS           106
SAO GONCALO                82
                         ...
ARMACAO DOS BUZIOS          6
RIO CLARO                   6
ITALVA                      6
CORDEIRO                    6
CARAPEBUS                   4
Name: count, Length: 87, dtype: int64

## 15. Distribuição por tipo de unidade

A coluna `DS_TIPO_UNIDADE` representa o tipo de estabelecimento de saúde.

O método `value_counts()` será utilizado para identificar a quantidade de registros pertencentes a cada tipo de unidade.

In [67]:
hospital_RJ['DS_TIPO_UNIDADE'].value_counts()

DS_TIPO_UNIDADE
HOSPITAL GERAL                  1944
HOSPITAL ESPECIALIZADO           882
PRONTO SOCORRO GERAL              87
UNIDADE MISTA                     36
PRONTO SOCORRO ESPECIALIZADO      15
Name: count, dtype: int64

## 16. Total de leitos existentes

A coluna `LEITOS_EXISTENTES` representa a quantidade de leitos existentes registrados nos estabelecimentos.

O método `sum()` será utilizado para calcular o total de leitos existentes na base do Rio de Janeiro.

In [68]:
hospital_RJ['LEITOS_EXISTENTES'].sum()

np.int64(264200)

## 17. Total de leitos SUS

A coluna `LEITOS_SUS` representa a quantidade de leitos destinados ao Sistema Único de Saúde (SUS).

O método `sum()` será utilizado para calcular o total de leitos SUS registrados.

In [69]:
hospital_RJ['LEITOS_SUS'].sum()

np.int64(145005)

## 18. Percentual de leitos destinados ao SUS

Foi calculada a proporção entre os leitos SUS e o total de leitos existentes.

O resultado foi multiplicado por 100 para convertê-lo em percentual.

O método `round()` foi utilizado para arredondar o resultado para duas casas decimais.

In [70]:
round((hospital_RJ['LEITOS_SUS'].sum()/hospital_RJ['LEITOS_EXISTENTES'].sum())*100, 2)

np.float64(54.88)

## 19. Total de leitos de UTI existentes

A coluna `UTI_TOTAL_EXIST` representa a quantidade de leitos de UTI
existentes registrados na base.

O método `sum()` será utilizado para calcular o total.

In [71]:
hospital_RJ['UTI_TOTAL_EXIST'].sum()

np.int64(48954)

## 20. Total de leitos de UTI destinados ao SUS

A coluna `UTI_TOTAL_SUS` representa os leitos de UTI destinados ao SUS.

O método `sum()` será utilizado para calcular o total.

In [72]:
hospital_RJ['UTI_TOTAL_SUS'].sum()

np.int64(14420)

## 21. Percentual  TOTAL DO SUS E EXIST 

Foi calculada a proporção entre o SUS e o total existentes.

O resultado foi multiplicado por 100 para convertê-lo em percentual.

O método `round()` foi utilizado para arredondar o resultado para duas casas decimais.

In [73]:
round((hospital_RJ['UTI_TOTAL_SUS'].sum()/hospital_RJ['UTI_TOTAL_EXIST'].sum())*100, 2)

np.float64(29.46)

## 22. Leitos de UTI adulto existentes

A coluna `UTI_ADULTO_EXIST` representa os leitos de UTI adulto
existentes nos estabelecimentos.

O método `sum()` será utilizado para calcular o total.

In [74]:
hospital_RJ['UTI_ADULTO_EXIST'].sum()

np.int64(33748)

## 23. Leitos de UTI adulto destinados ao SUS

A coluna `UTI_ADULTO_SUS` representa os leitos de UTI adulto
destinados ao SUS.

O método `sum()` será utilizado para calcular o total.

In [75]:
hospital_RJ['UTI_ADULTO_SUS'].sum()

np.int64(10696)

## 24. Percentual de UTI adulto destinada ao SUS

Será calculada a proporção de leitos de UTI adulto SUS em relação
ao total de leitos de UTI adulto existentes.

In [76]:
round((hospital_RJ['UTI_ADULTO_SUS'].sum()/hospital_RJ['UTI_ADULTO_EXIST'].sum())*100, 2)

np.float64(31.69)

## 25. Leitos de UTI pediátrica existentes

A coluna `UTI_PEDIATRICO_EXIST` representa os leitos de UTI
pediátrica existentes.

O método `sum()` será utilizado para calcular o total.

In [77]:
hospital_RJ['UTI_PEDIATRICO_EXIST'].sum()

np.int64(5111)

## 26. Leitos de UTI pediátrica destinados ao SUS

A coluna `UTI_PEDIATRICO_SUS` representa os leitos de UTI
pediátrica destinados ao SUS.

O método `sum()` será utilizado para calcular o total.

In [78]:
hospital_RJ['UTI_PEDIATRICO_SUS'].sum()

np.int64(1230)

## 27. Percentual de UTI pediátrica destinada ao SUS

Será calculada a proporção de leitos de UTI pediátrica SUS
em relação ao total de UTI pediátrica existente.

In [79]:
round((hospital_RJ['UTI_PEDIATRICO_SUS'].sum()/hospital_RJ['UTI_PEDIATRICO_EXIST'].sum())*100, 2)

np.float64(24.07)

## 28. Leitos de UTI neonatal existentes

A coluna `UTI_NEONATAL_EXIST` representa os leitos de UTI neonatal
existentes registrados na base.

In [80]:
hospital_RJ['UTI_NEONATAL_EXIST'].sum()

np.int64(8348)

## 29. Leitos de UTI neonatal destinados ao SUS

A coluna `UTI_NEONATAL_SUS` representa os leitos de UTI neonatal
destinados ao SUS.

In [81]:
hospital_RJ['UTI_NEONATAL_SUS'].sum()

np.int64(2332)

## 30. Percentual de UTI neonatal destinada ao SUS

Será calculada a proporção de leitos de UTI neonatal SUS
em relação ao total de UTI neonatal existente.

In [82]:
round((hospital_RJ['UTI_NEONATAL_SUS'].sum()/hospital_RJ['UTI_NEONATAL_EXIST'].sum())*100, 2)

np.float64(27.93)

## 31. Leitos de UTI coronariana existentes

A coluna `UTI_CORONARIANA_EXIST` representa os leitos de UTI
coronariana existentes nos estabelecimentos.

In [83]:
hospital_RJ['UTI_CORONARIANA_EXIST'].sum()

np.int64(1633)

## 32. Leitos de UTI coronariana destinados ao SUS

A coluna `UTI_CORONARIANA_SUS` representa os leitos de UTI
coronariana destinados ao SUS.

In [84]:
hospital_RJ['UTI_CORONARIANA_SUS'].sum()

np.int64(102)

## 33. Percentual de UTI coronariana destinada ao SUS

Será calculada a proporção de leitos de UTI coronariana SUS
em relação ao total de UTI coronariana existente.

In [85]:
round(hospital_RJ['UTI_CORONARIANA_SUS'].sum()/hospital_RJ['UTI_CORONARIANA_EXIST'].sum()*100, 2)

np.float64(6.25)

## 34. Leitos de UTI para queimados existentes

A coluna `UTI_QUEIMADO_EXIST` representa os leitos de UTI
para queimados existentes na base.

In [86]:
hospital_RJ['UTI_QUEIMADO_EXIST'].sum()

np.int64(114)

## 35. Leitos de UTI para queimados destinados ao SUS

A coluna `UTI_QUEIMADO_SUS` representa os leitos de UTI para
queimados destinados ao SUS.

In [87]:
hospital_RJ['UTI_QUEIMADO_SUS'].sum()

np.int64(60)

## 25. Percentual de UTI para queimados destinada ao SUS

Será calculada a proporção de leitos de UTI para queimados SUS
em relação ao total de leitos de UTI para queimados existentes.

In [88]:
round((hospital_RJ['UTI_QUEIMADO_SUS'].sum()/hospital_RJ['UTI_QUEIMADO_EXIST'].sum())*100, 2)

np.float64(52.63)

## Resumo da análise de leitos e UTIs

A análise exploratória da base do Rio de Janeiro identificou
2.964 registros distribuídos em 87 municípios.

Foram analisados os leitos hospitalares e diferentes categorias
de UTI, comparando a quantidade existente com a quantidade
destinada ao SUS.